language: android
dist: trusty
jdk:
  - openjdk11

env:
  global:
    - GODOT_LIB_VERSION=godot-lib.3.2.2.rc1.release
    - GODOT_LIB_URL=https://downloads.tuxfamily.org/godotengine/3.2.2/rc1/godot-lib.3.2.2.rc1.release.aar

android:
  components:
    - build-tools-30.0.0
    - android-30

# accepting android build-tools-30.0.0's license
before_install:
  - yes | sdkmanager "platforms;android-30"

script:
  - cd plugin
  # download dependency
  - wget -O ${GODOT_LIB_VERSION}/${GODOT_LIB_VERSION}.aar $GODOT_LIB_URL
  # Execute task 'verifyGoogleJavaFormat' to verify all *.java files are correctly formatted
  - ./gradlew verGJF
  # execute test cases
  - ./gradlew test
  # build aar library
  - ./gradlew build
