language: android
dist: trusty

android:
  components:
    - build-tools-30.0.0
    - android-30
  licenses:
    # accept all licenses
    - '.+'

before_install:
  - yes | sdkmanager "platforms;android-30"

script:
  - cd plugin
  - ./gradlew test
