language: android
dist: trusty

android:
  components:
    - build-tools-30.0.0
    - android-30
  licenses:
    # accept all licenses
    - '.+'

before_install:
  - yes | sdkmanager "platforms;android-30"

script:
  - cd plugin
  - wget -O godot-lib.3.2.2.rc1.release/godot-lib.3.2.2.rc1.release.aar https://downloads.tuxfamily.org/godotengine/3.2.2/rc1/godot-lib.3.2.2.rc1.release.aar 
  - ./gradlew test
