language: android
dist: trusty

env:
  global:
    - GODOT_LIB_VERSION=godot-lib.3.2.2.rc1.release
    - GODOT_LIB_URL=https://downloads.tuxfamily.org/godotengine/3.2.2/rc1/godot-lib.3.2.2.rc1.release.aar
    - GODOT_HEADLESS_VERSION=3.2.2
    - GODOT_HEADLESS=Godot_v3.2.2-stable_linux_headless.64
    - GODOT_HEADLESS_URL=https://downloads.tuxfamily.org/godotengine/3.2.2/Godot_v3.2.2-stable_linux_headless.64.zip
    - GUT_VERSION=7.0.0
    - GUT_URL=https://github.com/bitwes/Gut/archive/080c5f0a6eb54ed382ce840fe847b457c28e9dbb.zip
android:
  components:
    - build-tools-30.0.0
    - android-30

# accepting android build-tools-30.0.0's license
before_install:
  - yes | sdkmanager "platforms;android-30"

script:
  # front-facing api unit tests
  - cd api
  # download Gut (Godot unit testing) library
  - wget --max-redirect 0 -O Gut.zip $GUT_URL
  - unzip Gut.zip
  - cp -a Gut-${GUT_VERSION}/addons/ addons/

  # download Godot headless
  - wget -O ${GODOT_HEADLESS}.zip $GODOT_HEADLESS_URL
  - unzip ${GODOT_HEADLESS}.zip
  - chmod +x ${GODOT_HEADLESS}
  
  # run test cases
  - ./${GODOT_HEADLESS} --path $PWD --script addons/gut/gut_cmdln.gd -d -gexit -ginclude_subdirs -gdir=res://test


  # plugin unit tests
  - cd ../plugin
  # download dependency
  - wget -O ${GODOT_LIB_VERSION}/${GODOT_LIB_VERSION}.aar $GODOT_LIB_URL
  # Execute task 'verifyGoogleJavaFormat' to verify all *.java files are correctly formatted
  - ./gradlew verGJF
  # execute test cases
  - ./gradlew test
  # build aar library
  - ./gradlew build
